#!/usr/bin/env python
# coding=utf-8
"""Start/Stop a simple HTTP server."""
import sys
import os
import utils


if __name__ == "__main__":
    try:
        parser = utils.argparser()
        args = parser.parse_args()
        args.func(args)
    except utils.exception.DataProcessorError as e:
        print("ERROR: %s" % e.msg)
        sys.exit(1)
