#!/usr/bin/env python
# coding: utf-8

import os.path
import sys

sys.path = ([sys.path[0]]
            + [os.path.join(os.path.dirname(__file__), "../lib")]
            + sys.path[1:])
import dataprocessor as dp
sys.path = [sys.path[0]] + sys.path[2:]

import utils


def main():
    generator = dp.gencompletion.CompletionGenerator(
        "dpserver", utils.argparser())
    filename = dp.utility.path_expand(
        os.path.join(os.path.dirname(__file__),
                     "../zsh_completion", "_dpserver"))
    with open(filename, "w") as f:
        f.write(generator.get())
    return


if __name__ == "__main__":
    main()
